{work.map(({ name, startDate, endDate, position, summary, responsibilities = [], achievements = [], url, skills, location, location_type }) => {
```

```js
{responsibilities.map((responsibility: string) => (
```

```js
{achievements.map((achievement: string) => (